services:
  - type: web
    name: flask-app
    runtime: python
    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FLASK_ENV
        value: production
