services:
  - type: web
    name: fastapi-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --worker-class uvicorn.workers.UvicornWorker
    envVars:
      - key: PORT
        value: "10000"
      - key: PYTHON_VERSION
        value: "3.9.0"
